# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-dom0"
BBFILE_PATTERN_xen-dom0 := "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-dom0 = "19"

LAYERSERIES_COMPAT_xen-dom0 = "kirkstone scarthgap"

