#!/bin/sh
# Change domain configuration to boot from storage configured by u-boot

DOMD_CFG_FILE="/etc/xen/domd.cfg"

# detect boot storage device
BOOT_STORAGE=`grep 'boot_dev=' /proc/device-tree/chosen/u-boot,bootconf | sed -e 's/.*boot_dev=//' -e 's/#.*//'`
if [ -z "$BOOT_STORAGE" ] ; then
    BOOT_STORAGE=mmcblk0
    echo "WARNING! Using default storage: ${BOOT_STORAGE}"
fi

# Special case for NFS - we want to quite different cmd line
if [ $BOOT_STORAGE = nfs ] ; then
    MY_IP=`cat /proc/device-tree/boot_dev/my_ip | tr -d '\000'`
    SERVER_IP=`cat /proc/device-tree/boot_dev/nfs_server_ip  | tr -d '\000'`
    NFS_DIR=`cat /proc/device-tree/boot_dev/nfs_dir | tr -d '\000'`
    if [ -z "$MY_IP" ] ; then
	MY_IP="192.168.1.2"
	echo "WARNING! Using default ip address ${MY_IP}"
    fi
    if [ -z "$SERVER_IP" ] ; then
	SERVER_IP="192.168.1.100"
	echo "WARNING! Using default server ip address ${SERVER_IP}"
    fi
    if [ -z "$NFS_DIR" ] ; then
	NFS_DIR="/srv/domd"
	echo "WARNING! Using default NFS directory ${NFS_DIR}"
    fi
    BOOT_STR="nfs nfsroot=${SERVER_IP}:${NFS_DIR},vers=3 ip=${MY_IP}:::::eth0"
    # Escape slahes ( / ->\/ )
    BOOT_STR=`echo "${BOOT_STR}" | sed "s/\//\\\\\\\\\//g"`

    echo "Mangling domain configuration: setting storage to network boot"
    sed -i "s/STORAGE_PART[0-9]/${BOOT_STR}/g" $DOMD_CFG_FILE
    exit 0
fi

# guess partition prefix, e.g. "" for sda2 or "p" for mmcblk1p2
PART_PREFIX=""
if echo "${BOOT_STORAGE}" | grep -q -e 'mmc' -e 'nvme'; then
   PART_PREFIX="p"
fi
STORAGE_PART="${BOOT_STORAGE}${PART_PREFIX}"

# now make up the configuration
echo "Mangling domain configuration: setting storage to ${BOOT_STORAGE}"
sed -i "s/STORAGE_PART/${STORAGE_PART}/g" $DOMD_CFG_FILE

# Remove ramdisk when using MMC
if echo "${BOOT_STORAGE}" | grep -q -e 'mmc'; then
   sed -i "s/ramdisk.*//g" $DOMD_CFG_FILE
fi

# Memory setup
TOTAL_MEMORY=$(xl info | grep total_memory | sed "s/.*: //")
if [[ "${TOTAL_MEMORY}" == "16384" ]]; then
    sed -i "s/memory = .*/memory = 6144/g" $DOMD_CFG_FILE
fi

# Setup devicetree overlay files
BOOTCONF=$(cat /proc/device-tree/chosen/u-boot,bootconf)
if [ -n "$BOOTCONF" ] ; then
    pushd /lib/xen/boot
    DT_OVERLAY=""
    for conf in i $(echo $BOOTCONF | sed 's/#/ /g'); do
        case ${conf} in
            # J1
            "j1-imx219") DT_OVERLAY+=" r8a779g3-sparrow-hawk-camera-j1-imx219.dtbo";;
            "j1-imx462") DT_OVERLAY+=" r8a779g3-sparrow-hawk-camera-j1-imx462.dtbo";;
            "j1-imx708") DT_OVERLAY+=" r8a779g3-sparrow-hawk-camera-j1-imx708.dtbo";;
            # J2
            "j2-imx219") DT_OVERLAY+=" r8a779g3-sparrow-hawk-camera-j2-imx219.dtbo";;
            "j2-imx462") DT_OVERLAY+=" r8a779g3-sparrow-hawk-camera-j2-imx462.dtbo";;
            "j2-imx708") DT_OVERLAY+=" r8a779g3-sparrow-hawk-camera-j2-imx708.dtbo";;
            # J4
            "rpi-display-2-7in") DT_OVERLAY+=" r8a779g3-sparrow-hawk-rpi-display-2-7in.dtbo";;
            "rpi-display-2-5in") DT_OVERLAY+=" r8a779g3-sparrow-hawk-rpi-display-2-5in.dtbo";;
            "wavesharei-panel") DT_OVERLAY+=" r8a779g3-sparrow-hawk-dsi-waveshare-panal.dtbo";;
            # Others
            "fan-pwm") DT_OVERLAY+=" r8a779g3-sparrow-hawk-fan-pwm.dtbo";;
            "fan-argon40") DT_OVERLAY+=" r8a779g3-sparrow-hawk-fan-argon40.dtbo";;
        esac
    done

    fdtoverlay -i domd.dtb -o domd-fixed.dtb `echo "${DT_OVERLAY}" |sed 's/,/ /g'`
    if [[ -e ./domd-fixed.dtb ]]; then
        sed -i "s|/domd.dtb|/domd-fixed.dtb|g" $DOMD_CFG_FILE
    fi
    popd
fi

