# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-domx"
BBFILE_PATTERN_xen-domx = "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-domx = "13"

LAYERSERIES_COMPAT_xen-domx = "dunfell kirkstone"

