#!/bin/sh
# Change domain configuration to boot from storage configured by u-boot

# This script gets the 'MODE' parameter, which is not used right now.
# It was added to cover the 'virito' diff logic. Being kept even
# without the usage to have similar aproach in both DomU and DomA.
# In 'domu-set-root' it is used for real.
MODE="$1"

DOMA_CFG_FILE="/etc/xen/doma.cfg"

# detect boot storage device
BOOT_STORAGE=`grep 'boot_dev=' /proc/device-tree/chosen/u-boot,bootconf | sed -e 's/.*boot_dev=//' -e 's/#.*//'`
if [ -z "$BOOT_STORAGE" ] ; then
    BOOT_STORAGE=mmcblk0
    echo "WARNING! Using default storage: ${BOOT_STORAGE}"
fi

# Special case for NFS - we can't boot Android from NFS
if [ $BOOT_STORAGE = nfs ] ; then
    BOOT_STORAGE=mmcblk0
    echo "Using eMMC storage: ${BOOT_STORAGE} instead of NFS"
fi

if [[ -e /etc/xen/domu.cfg ]]; then
    # if domu is enabled, Partition will be changed
    sed -i "s/STORAGE_PART3/STORAGE_PART4/g" $DOMA_CFG_FILE
fi

# guess partition prefix, e.g. "" for sda2 or "p" for mmcblk1p3
PART_PREFIX=""
if echo "${BOOT_STORAGE}" | grep -q -e 'mmc' -e 'nvme'; then
   PART_PREFIX="p"
fi
STORAGE_PART="${BOOT_STORAGE}${PART_PREFIX}"

# now make up the configuration
echo "Mangling domain configuration: setting storage to ${BOOT_STORAGE}"
sed -i "s/STORAGE_PART/${STORAGE_PART}/g" $DOMA_CFG_FILE

# Memory setup
TOTAL_MEMORY=$(xl info | grep total_memory | sed "s/.*: //")
if [[ "${TOTAL_MEMORY}" == "16384" ]]; then
    sed -i "s/memory = .*/memory = 6144/g" $DOMA_CFG_FILE
fi

# Override DomA boot device
DOMA_STORAGE=`grep 'doma_dev=' /proc/device-tree/chosen/u-boot,bootconf | sed -e 's/.*doma_dev=//' -e 's/#.*//'`
if [ -n "$DOMA_STORAGE" ] ; then
    sed -i "s|/dev/${STORAGE_PART}3|${DOMA_STORAGE}|g" $DOMA_CFG_FILE
fi

