# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-domd-virtio"
BBFILE_PATTERN_xen-domd-virtio = "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-domd-virtio = "20"

LAYERSERIES_COMPAT_xen-domd-virtio = "kirkstone scarthgap"

