# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-domu"
BBFILE_PATTERN_xen-domu = "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-domu = "5"

LAYERSERIES_COMPAT_xen-domu = "dunfell kirkstone"

