# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "xen-domd"
BBFILE_PATTERN_xen-domd = "^${LAYERDIR}/"
BBFILE_PRIORITY_xen-domd = "20"

LAYERSERIES_COMPAT_xen-domd = "dunfell kirkstone"

